
package org.jgp.system.views;

import java.awt.Color;
import org.jgp.system.controller.loginController;
import org.jgp.system.models.Users;
import org.jgp.system.models.UsersDao;


public class LoginSystem extends javax.swing.JFrame {
    
   Users us = new Users();
   UsersDao usDao = new UsersDao();
  int xMouse, yMouse;
  
    public LoginSystem() {
        initComponents();
        loginController users = new loginController(us, usDao, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        iconsuser = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        boxUsername = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        boxPassword = new javax.swing.JPasswordField();
        panelExit = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        pandel2 = new javax.swing.JPanel();
        btnlogin = new org.jgp.system.views.swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        setMaximumSize(new java.awt.Dimension(300, 500));
        setUndecorated(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(80, 70, 170));
        panel.setMaximumSize(new java.awt.Dimension(300, 500));
        panel.setMinimumSize(new java.awt.Dimension(300, 500));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconsuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jgp/system/img/icons8-user-100.png"))); // NOI18N
        panel.add(iconsuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        username.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");
        panel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        boxUsername.setBackground(new java.awt.Color(255, 255, 255));
        boxUsername.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxUsername.setForeground(new java.awt.Color(204, 204, 204));
        boxUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxUsername.setText("Ingrese su nombre de ususario");
        boxUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxUsernameMousePressed(evt);
            }
        });
        boxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUsernameActionPerformed(evt);
            }
        });
        panel.add(boxUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 260, 30));

        password.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        boxPassword.setBackground(new java.awt.Color(255, 255, 255));
        boxPassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxPassword.setForeground(new java.awt.Color(204, 204, 204));
        boxPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxPassword.setText("************");
        boxPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxPasswordMousePressed(evt);
            }
        });
        boxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPasswordActionPerformed(evt);
            }
        });
        panel.add(boxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 260, 30));

        panelExit.setBackground(new java.awt.Color(240, 240, 240));
        panelExit.setForeground(new java.awt.Color(240, 240, 240));

        Exit.setBackground(new java.awt.Color(240, 240, 240));
        Exit.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 51, 51));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setToolTipText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExitLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExitLayout.createSequentialGroup()
                .addComponent(Exit)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panel.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        pandel2.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout pandel2Layout = new javax.swing.GroupLayout(pandel2);
        pandel2.setLayout(pandel2Layout);
        pandel2Layout.setHorizontalGroup(
            pandel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        pandel2Layout.setVerticalGroup(
            pandel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        panel.add(pandel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 500));

        btnlogin.setText("LOGIN");
        panel.add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUsernameActionPerformed
       
    }//GEN-LAST:event_boxUsernameActionPerformed

    private void boxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPasswordActionPerformed
       
    }//GEN-LAST:event_boxPasswordActionPerformed

    private void boxUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxUsernameMousePressed
         if (boxUsername.getText().equals("Ingrese su nombre de ususario")) {
            boxUsername.setText("");
            boxUsername.setForeground(Color.BLACK);
        }
        if (String.valueOf(boxPassword.getPassword()).isEmpty()) {
            boxPassword.setText("************");
            boxPassword.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxUsernameMousePressed

    private void boxPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPasswordMousePressed
        if (String.valueOf(boxPassword.getPassword()).equals("************")) {
            boxPassword.setText("");
            boxPassword.setForeground(Color.BLACK);
        }
        if (boxUsername.getText().isEmpty()) {
            boxUsername.setText("Ingrese su nombre de ususario");
            boxUsername.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxPasswordMousePressed

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
         panelExit.setBackground(new Color(255,51,51));
        Exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
         panelExit.setBackground(new Color(240,240,240));
        Exit.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
          System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    public javax.swing.JPasswordField boxPassword;
    public javax.swing.JTextField boxUsername;
    public org.jgp.system.views.swing.Button btnlogin;
    private javax.swing.JLabel iconsuser;
    private javax.swing.JPanel pandel2;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelExit;
    private javax.swing.JLabel password;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
