/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jgp.system.views;

import java.awt.Color;

/**
 *
 * @author javie
 */
public class RegisterLoginSystem extends javax.swing.JFrame {

  int xMouse, yMouse;
  
    public RegisterLoginSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        iconsuser = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        boxUsername = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        boxPassword = new javax.swing.JPasswordField();
        rePassword = new javax.swing.JLabel();
        boxRePassword = new javax.swing.JPasswordField();
        fullName = new javax.swing.JLabel();
        boxFullName = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        boxEmail = new javax.swing.JTextField();
        panelExit = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 240, 240));
        setUndecorated(true);
        setResizable(false);

        panel.setBackground(new java.awt.Color(80, 70, 170));
        panel.setMaximumSize(new java.awt.Dimension(300, 500));
        panel.setMinimumSize(new java.awt.Dimension(300, 500));
        panel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelMouseDragged(evt);
            }
        });
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelMousePressed(evt);
            }
        });
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconsuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jgp/system/img/icons8-user-100.png"))); // NOI18N
        panel.add(iconsuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jgp/system/img/icons8-accede-redondeado-derecho-64.png"))); // NOI18N
        login.setToolTipText("lOGIN");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 90, 80));

        username.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");
        panel.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        boxUsername.setBackground(new java.awt.Color(255, 255, 255));
        boxUsername.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxUsername.setForeground(new java.awt.Color(204, 204, 204));
        boxUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxUsername.setText("Ingrese su nombre de ususario");
        boxUsername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxUsernameMousePressed(evt);
            }
        });
        boxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUsernameActionPerformed(evt);
            }
        });
        panel.add(boxUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 260, 30));

        password.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");
        panel.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        boxPassword.setBackground(new java.awt.Color(255, 255, 255));
        boxPassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxPassword.setForeground(new java.awt.Color(204, 204, 204));
        boxPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxPassword.setText("************");
        boxPassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxPasswordMousePressed(evt);
            }
        });
        boxPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPasswordActionPerformed(evt);
            }
        });
        panel.add(boxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 260, 30));

        rePassword.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        rePassword.setForeground(new java.awt.Color(255, 255, 255));
        rePassword.setText("Password:");
        panel.add(rePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        boxRePassword.setBackground(new java.awt.Color(255, 255, 255));
        boxRePassword.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxRePassword.setForeground(new java.awt.Color(204, 204, 204));
        boxRePassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxRePassword.setText("************");
        boxRePassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxRePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxRePasswordMousePressed(evt);
            }
        });
        boxRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxRePasswordActionPerformed(evt);
            }
        });
        panel.add(boxRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 260, 30));

        fullName.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        fullName.setForeground(new java.awt.Color(255, 255, 255));
        fullName.setText("Nombre Completo: ");
        panel.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        boxFullName.setBackground(new java.awt.Color(255, 255, 255));
        boxFullName.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxFullName.setForeground(new java.awt.Color(204, 204, 204));
        boxFullName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxFullName.setText("Ingrese su nombre completo");
        boxFullName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxFullName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxFullNameMousePressed(evt);
            }
        });
        boxFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFullNameActionPerformed(evt);
            }
        });
        panel.add(boxFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 260, 30));

        Email.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email: ");
        panel.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        boxEmail.setBackground(new java.awt.Color(255, 255, 255));
        boxEmail.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        boxEmail.setForeground(new java.awt.Color(204, 204, 204));
        boxEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        boxEmail.setText("Ingrese su Email");
        boxEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(204, 204, 204)));
        boxEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boxEmailMousePressed(evt);
            }
        });
        boxEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxEmailActionPerformed(evt);
            }
        });
        panel.add(boxEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 260, 30));

        panelExit.setBackground(new java.awt.Color(240, 240, 240));
        panelExit.setForeground(new java.awt.Color(240, 240, 240));

        Exit.setBackground(new java.awt.Color(240, 240, 240));
        Exit.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 51, 51));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setToolTipText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelExitLayout = new javax.swing.GroupLayout(panelExit);
        panelExit.setLayout(panelExitLayout);
        panelExitLayout.setHorizontalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExitLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelExitLayout.setVerticalGroup(
            panelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExitLayout.createSequentialGroup()
                .addComponent(Exit)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        panel.add(panelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        panel2.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        panel.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUsernameActionPerformed
       
    }//GEN-LAST:event_boxUsernameActionPerformed

    private void boxPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPasswordActionPerformed
       
    }//GEN-LAST:event_boxPasswordActionPerformed

    private void boxUsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxUsernameMousePressed
         if (boxUsername.getText().equals("Ingrese su nombre de ususario")) {
            boxUsername.setText("");
            boxUsername.setForeground(Color.BLACK);
        }
        if (String.valueOf(boxPassword.getPassword()).isEmpty()) {
            boxPassword.setText("************");
            boxPassword.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxRePassword.getPassword()).isEmpty()) {
            boxRePassword.setText("************");
            boxRePassword.setForeground(Color.lightGray);
        }
        
         if (boxFullName.getText().isEmpty()) {
            boxFullName.setText("Ingrese su nombre completo");
            boxFullName.setForeground(Color.lightGray);
        }
          if (boxEmail.getText().isEmpty()) {
            boxEmail.setText("Ingrese su Email");
            boxEmail.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxUsernameMousePressed

    private void boxPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxPasswordMousePressed
        if (String.valueOf(boxPassword.getPassword()).equals("************")) {
            boxPassword.setText("");
            boxPassword.setForeground(Color.BLACK);
        }
        if (boxUsername.getText().isEmpty()) {
            boxUsername.setText("Ingrese su nombre de ususario");
            boxUsername.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxRePassword.getPassword()).isEmpty()) {
            boxRePassword.setText("************");
            boxRePassword.setForeground(Color.lightGray);
        }
        
         if (boxFullName.getText().isEmpty()) {
            boxFullName.setText("Ingrese su nombre completo");
            boxFullName.setForeground(Color.lightGray);
        }
          if (boxEmail.getText().isEmpty()) {
            boxEmail.setText("Ingrese su Email");
            boxEmail.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxPasswordMousePressed

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseEntered
         panelExit.setBackground(new Color(255,51,51));
        Exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_ExitMouseEntered

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseExited
         panelExit.setBackground(new Color(240,240,240));
        Exit.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_ExitMouseExited

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
          System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void panelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelMousePressed

    private void panelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelMouseDragged

    private void boxRePasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxRePasswordMousePressed
        if (String.valueOf(boxRePassword.getPassword()).equals("************")) {
            boxRePassword.setText("");
            boxRePassword.setForeground(Color.BLACK);
        }
        if (boxUsername.getText().isEmpty()) {
            boxUsername.setText("Ingrese su nombre de ususario");
            boxUsername.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxPassword.getPassword()).isEmpty()) {
            boxPassword.setText("************");
            boxPassword.setForeground(Color.lightGray);
        }
        
         if (boxFullName.getText().isEmpty()) {
            boxFullName.setText("Ingrese su nombre completo");
            boxFullName.setForeground(Color.lightGray);
        }
          if (boxEmail.getText().isEmpty()) {
            boxEmail.setText("Ingrese su Email");
            boxEmail.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxRePasswordMousePressed

    private void boxRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxRePasswordActionPerformed

    private void boxFullNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxFullNameMousePressed
       if (boxFullName.getText().equals("Ingrese su nombre completo")) {
            boxFullName.setText("");
            boxFullName.setForeground(Color.BLACK);
        }
        if (boxUsername.getText().isEmpty()) {
            boxUsername.setText("Ingrese su nombre de ususario");
            boxUsername.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxPassword.getPassword()).isEmpty()) {
            boxPassword.setText("************");
            boxPassword.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxRePassword.getPassword()).isEmpty()) {
            boxRePassword.setText("************");
            boxRePassword.setForeground(Color.lightGray);
        }        
         
          if (boxEmail.getText().isEmpty()) {
            boxEmail.setText("Ingrese su Email");
            boxEmail.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxFullNameMousePressed

    private void boxFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFullNameActionPerformed

    private void boxEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxEmailMousePressed
        if (boxEmail.getText().equals("Ingrese su Email")) {
            boxEmail.setText("");
            boxEmail.setForeground(Color.BLACK);
        }
        if (boxUsername.getText().isEmpty()) {
            boxUsername.setText("Ingrese su nombre de ususario");
            boxUsername.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxPassword.getPassword()).isEmpty()) {
            boxPassword.setText("************");
            boxPassword.setForeground(Color.lightGray);
        }
         if (String.valueOf(boxRePassword.getPassword()).isEmpty()) {
            boxRePassword.setText("************");
            boxRePassword.setForeground(Color.lightGray);
        }        
         
          if (boxFullName.getText().isEmpty()) {
            boxFullName.setText("Ingrese su nombre completo");
            boxFullName.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_boxEmailMousePressed

    private void boxEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLoginSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterLoginSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Exit;
    private javax.swing.JTextField boxEmail;
    private javax.swing.JTextField boxFullName;
    private javax.swing.JPasswordField boxPassword;
    private javax.swing.JPasswordField boxRePassword;
    private javax.swing.JTextField boxUsername;
    private javax.swing.JLabel fullName;
    private javax.swing.JLabel iconsuser;
    private javax.swing.JLabel login;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panelExit;
    private javax.swing.JLabel password;
    private javax.swing.JLabel rePassword;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
